### ISSUE TITLE
Failed to solve COPY commands

### ISSUE THREAD

**Issue by justnajm** [ccallazans/ai-video-generator#7]
Hi,

Thanks for great share, I am using windows 10 pro, have installed docker recently on my machine, I was not able to use make command, so used 'composer up' instead, it has complete all steps but failed on last ones:

------
 > [ollama builder 2/3] COPY ./setup-ollama.sh ./setup-ollama.sh:
------
------
 > [ollama stage-1 2/2] COPY --from=builder /root/.ollama /root/.ollama:
------
failed to solve: failed to compute cache key: failed commit on ref "layer-sha256:9271f581950b2a19fd60ee3fd5156e49b01efe25a87e8d8a4d2b5f6ffacf2555": commit failed: rename /var/lib/desktop-containerd/daemon/io.containerd.content.v1.content/ingest/0316bfa5e7807992488bafb3c86316784b0c89de1dcd5bd7553262dc20c95aff/data /var/lib/desktop-containerd/daemon/io.containerd.content.v1.content/blobs/sha256/9271f581950b2a19fd60ee3fd5156e49b01efe25a87e8d8a4d2b5f6ffacf2555: no such file or directory: unknown

please let me know what I am doing wrong, I want to try the image, actually interested in urdu language, and most importantly the 'captions are generated from the audio' part, I want to try and build an image on top of your working idea. Let me know if you have any tips regarding language 'urdu'.

Thanks for amazing work :)

**Comment by Saqib92** [comment]
facing same error.. 
Did you find any solution?

**Comment by justnajm** [comment]
Sorry Saqib, I had no response, still on hold on my pc

**Comment by ccallazans** [comment]
Suggestions:

1 - Are you running on Windows or WSL?

2 - The error might be in the docker-compose.yaml file. Specifically, this section:

```
  services:
    ollama:
      build:
        context: .
        dockerfile: Dockerfile.ollama
      ports: ["11434:11434"]
      volumes:
        - ollama_data:/root/.ollama  # This filesystem works for Linux; I'm not sure if it works for Windows.
      networks:
        - net
```

You could try changing the directory or deleting the volume (though this is not ideal since you’d need to re-pull everything on each run).

3 - In the Dockerfile.ollama, try changing the line:

`COPY ./setup-ollama.sh ./setup-ollama.sh` to `COPY setup-ollama.sh setup-ollama.sh`

4 - Additionally, pay attention to the file encoding. On Windows, files are typically encoded with CRLF, while on Linux, they use LF. To ensure compatibility, you might want to delete and recreate the Dockerfile.ollama file so it uses the correct encoding for Windows.

Sorry for the delay I saw your comment earlier but only had a chance to review it now.
